name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - obspy>=1.4.1
  - sqlalchemy
  - flask
  - flask-admin
  - flask-wtf
  - markdown
  - scandir
  - logbook
  - pytables
  - click
  - click-plugins
  - pandas
  - folium
  - pip
  - pymysql
  - xarray
  - sqlalchemy-utils
  - pooch
  - pytest
  - pytest-order
  - pytest-cov
  - coverage
  - pip:
      - git+https://github.com/regeirk/pycwt
      - click-command-tree

