name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - obspy>=1.4.1
  - sqlalchemy
  - flask
  - flask-admin
  - flask-wtf
  - markdown
  - scandir
  - logbook
  - pytables
  - click
  - pandas
  - folium
  - pip
  - pymysql
  - xarray
  - sqlalchemy-utils

