# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: c

services:
  - mysql

matrix:
  include:
    # do one build run with our minimum dependencies
    # (or, well, at least the lowest version number that is available through
    #  anaconda..)
    - os: linux
      env: PYTHON_VERSION=2.7

    - os: linux
      env: PYTHON_VERSION=3.7

    - os: osx
      env: PYTHON_VERSION=2.7

    - os: osx
      env: PYTHON_VERSION=3.7


sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
    else
      export OS="Linux";
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update > /dev/null && brew install mariadb && brew services start mariadb; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then mkdir /usr/local/etc/my.cnf.d; fi
  # MySQL database
  - mysql -u root -e "create database msnoise;"
  # Python and related stuff
  - if [[ "${PYTHON_VERSION:0:1}" == '2' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-${OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q --yes conda
  # Installs required packages
  - conda install --yes -q pip python=$PYTHON_VERSION
  - conda install --yes -q numpy scipy matplotlib pandas sqlalchemy
  - conda install --yes -q sphinx jinja2 flask pymysql click
  - conda install --yes -q lxml pyqt
  - conda install --yes -q -c conda-forge obspy
  - conda install --yes -q -c conda-forge flask-admin markdown codecov
  - pip install logbook
  - ls -la

install:
  - python setup.py install
  - cd

script:
  - mkdir empty
  - cd empty
  - msnoise --help
  - msnoise bugreport -s -m -e
  - cd ..
  - mkdir MSNoiseTest
  - cd MSNoiseTest
  - coverage run --include='*/msnoise/*' -m msnoise.test.tests
  - codecov