# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: https://stackoverflow.com/a/13751649
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\misc\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: 64
      MINICONDA: C:\Miniconda-x64

    - PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64
      MINICONDA: C:\Miniconda36-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

platform:
  - x64

services:
  - mysql

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy"
  - activate test-environment
  # Install default dependencies
  - "%CMD_IN_ENV% conda install --yes -q pip"
  - "%CMD_IN_ENV% conda install --yes -q scipy matplotlib pandas sqlalchemy"
  - "%CMD_IN_ENV% conda install --yes -q sphinx jinja2 flask pymysql click"
  - "%CMD_IN_ENV% conda install --yes -q lxml"
  - "%CMD_IN_ENV% conda install --yes -c conda-forge obspy"
  - "%CMD_IN_ENV% conda install --yes -c conda-forge flask-admin markdown"
  # list package versions
  - "%CMD_IN_ENV% conda list"

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
  - python setup.py develop
  - conda info --envs
  - echo %CD%
  - ps: mkdir test
  - ps: cd test
  - echo %CD%
  - msnoise bugreport -m
  - msnoise test
